"""eerste stap van deze database!

Revision ID: fae621105ea0
Revises: 
Create Date: 2019-11-21 20:55:48.216023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae621105ea0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('woorden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('woord', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('woorden')
    # ### end Alembic commands ###
